#message:30:(Name_HP_Plus_P) {
HP Plus P[End]
}

#message:30:(ItemFullDesc_HP_Plus_P) {
Increases partner maximum HP[BR]
by 5.[End]
}

#message:30:(ItemShortDesc_HP_Plus_P) {
Increases partner maximum HP[BR]
by 5.[End]
}

#message:30:(Name_Power_Plus_P) {
Power Plus P[End]
}

#message:30:(ItemFullDesc_Power_Plus_P) {
Increases the current partner's[BR]
attack powers by 1.[End]
}

#message:30:(ItemShortDesc_Power_Plus_P) {
Increases the current partner's[BR]
attack powers by 1.[End]
}
