#message:30:(Name_HP_Plus_P) {
HP Plus P[End]
}

#message:30:(ItemFullDesc_HP_Plus_P) {
Increases partner maximum HP[BR]
by 5.[End]
}

#message:30:(ItemShortDesc_HP_Plus_P) {
Increases partner maximum HP[BR]
by 5.[End]
}

#message:30:(Name_P_UP_D_DOWN_P) {
P-Up D-Down P[End]
}

#message:30:(ItemFullDesc_P_UP_D_DOWN_P) {
Increase damage dealt AND[BR]
received by 1.[END]
}

#message:30:(ItemShortDesc_P_UP_D_DOWN_P) {
Increase damage dealt AND[BR]
received by 1.[END]
}

#message:30:(Name_P_DOWN_D_UP_P) {
P-Down D-Up P[End]
}

#message:30:(ItemFullDesc_P_DOWN_D_UP_P) {
Decrease damage dealt AND[BR]
received by 1.[END]
}

#message:30:(ItemShortDesc_P_DOWN_D_UP_P) {
Decrease damage dealt AND[BR]
received by 1.[END]
}
